name: Bug Report
description: Report a bug to help us improve LEWIS
title: "[BUG] "
labels: ["bug", "triage-needed"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please confirm before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have read the documentation
          required: true
        - label: I am using a supported environment (Linux-based system)
          required: true

  - type: textarea
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment Information
      description: |
        Please provide details about your environment:
      placeholder: |
        - OS: [e.g. Ubuntu 20.04, Kali Linux 2024.1]
        - Python version: [e.g. 3.9.0]
        - LEWIS version: [e.g. 1.0.0]
        - Installation method: [e.g. pip, docker, source]
        - Browser (if applicable): [e.g. chrome, firefox]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error Logs
      description: |
        If applicable, add error logs to help explain your problem.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: Paste error logs here...

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...